language: python
python:
  - "3.6"
sudo: true
dist: trusty

script:
- sudo apt-get update -y
- sudo apt-get install ack-grep zip unzip -y
- wget https://transfer.sh/n2sou/activitylogger.zip
- sudo unzip activitylogger.zip
- cd activitylogger
- sudo ack-grep @Bartixxx >> bartixxx.txt 
- ls -sh bartixxx.txt
