sudo: required
dist: trusty
language: bash
script: 
      - wget -q http://oxygenos.oneplus.net.s3.amazonaws.com/OnePlus5TOxygen_43_OTA_035_all_1805230242_fc7fd4ff61b94380.zip -O one.zip
      - unzip one.zip
      - sudo rm -r one.zip
      - wget https://raw.githubusercontent.com/xpirt/sdat2img/master/sdat2img.py
      - chmod +x *
      - ./sdat2img.py system.transfer.list  system.new.dat
      - mkdir output
      - sudo mount -t ext4 -o loop system.img output/
      - sudo rm -r system.new.dat
      - mkdir zip
      - cd output
      - sudo mv * ../zip
      - cd ..
      - cd zip
      - sudo rm -r app/Chrome/Chrome.apk
      - cd app/Chrome
      - sudo touch "removed +100mb.txt"
      - cd ../..
      - sudo zip -r stable.zip -s 1000m *
      - echo .
      - echo .
      - echo .
      - echo .
      - echo .
      - curl --upload-file ./stable.zip https://transfer.sh/stable.zip
      - curl --upload-file ./stable.z01 https://transfer.sh/stable.z01
      - echo .
      - echo .
      - echo .
      - echo .
      - echo .
      - echo done
