sudo: required
dist: trusty
language: bash
jobs:
  include:
    - stage: test
      script: 
      - bash <(curl -sSL https://raw.githubusercontent.com/serverscope/serverscope-benchmark/master/install-serverscope.sh) -uvc -e "mcbplay1@gmail.com" -p "free|travis" -i speedtest,download,dd,fio
