sudo: false
dist: trusty
language: bash
script:
- sudo mkdir /home/linuxbrew
- sudo git clone https://github.com/Linuxbrew/brew /home/linuxbrew/.linuxbrew
- PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
- brew update
- brew install maven
