# Ruby is our language as asciidoctor is a ruby gem.

lang: ruby

script:
- sudo chmod +x push.sh
- touch test2.txt

after_success:

- ./push.sh

env:

global:

 secure: "YE6yNN7bF3VyJLLQ2Ed/vEu3R8f0hjDk4h2XlK+C7zRwjLz8uBfrIwlBy6HJica45/ZgDCk7QxWP/Ev/oiZcM9uEP1nosOqbQklX0N4YtC9yzaJD+9FF9/NNkC7mhJ3VQaGs2FaLZUp6zH78DV4JUT7ozO28Cx0rub9xdTnKBHBB6kNvgpjgSP6aJvt6p6pv7W5UR37jnTeY+XpyCJN9CGfRG1BOEBcz80sNzDpwGYC+/BmGkAUCYRFI+RHZ4nloGpLgt6QR9TzCx10YzuDZuvCJVxpX4jPRcBLI+hM8GRTVGclOc5lKht0xIC3+M4bkELZc5PLHtXJEa840zhpH+B/8Im9FcieSABUv8JOVQJsFsV9TPfdamW4jxwRJnrWIsGG+Wj3hy9Mz9Oqv6prMQDM2KysFT3OFGM8tITPTy3tZ4A27hffPyBi8uSf0m01wqFWi0saC93dJN7djrQ6RV8agd8PgLtc79R6xw66RmodPPYnTntr2NRfqOgEo2LkFHZycjz12yc/MnW0nV7x10C2aCJQlCHFAtdp+xROO9B2grorDom6SGuYnUFTjUPRJgTuHx95+IApNc+Uvl2KBdd1FwXEB351W0FM/jIDhrIoMjrpBRHTTfJ7ntKk3fj/PBl3KYXr94u+eZ/6WFvEtCBXxGccUQd41w2HiFnj9oQg="
