language: bash
sudo: true

script:
- sudo apt-get update -y
- sudo apt-get install zip unzip -y
- .travis/push.sh

 secure: "CTLRUEhgdmWjAvVXG0cun8gGPZrDNuBi7Mdi3UUPRB+rCnbt5tre0VPM/yGOVOxs7QUUQk+b89OAct7qmtvKWqEg0M2O8MGfQ0yIS3ak7v6XfedhU+6io3VEsfDFp6IglQFM3cVw0VpRK3glPO+7GkIGTAzBCFjmKlaphUAcs/s9lzZ5MopwaH7nmxNzKa55H7kAvd1TzTBEHnkNNxP4Zq4DkQ4USvwGmbYyi4HTQkBFGdKWmekXdwjDSyqOkfeLg8cmA13wec0K9yw5JnVbsYCA8nDHjTGsUgQoiVbSXyGX/O1gLwAc/hXiK9ZZbe2Cuuo5DniVuMeoInY1lXObVelR9QY8XkIkMX+TCP9bIBadVR0uQdfFIiqcLvOfdW0AgwhXmht3r3WpKbMaEJTrEOViJdoG9jKLIdx/9hlzFgpsuoyqmBGhmNwcmAuF0MUqAhJJz80IHvBmFkIbrruAEqYRu2Lsy32E8RbH6M3HO+M23Od2TupAMqheKuICIIz6T3CqlehzThV99mHm3ri7QKE6zM+6n35c7yUgpgwQffnMCr4CvkikXNh19G8HUU0C96zB3D1KmlzQuB34M9W1PvSC7iqayc7WUUQQIuxJgHbpjsrVtCI7WxJeyd+ZJOlH2koPkBAt+o4ZEX7bc8uPfleTML+6oLJ8r9DzTchYQwU="
