language: ruby

rvm:

- 2.0.0

env:

global:

- UZYT="Bartixxx32"

- EMAILBP="mcbplay1@gmail.com"

- REPOBART="spdtravis"

- FILESBART="foo.txt"

- GH_REPO="github.com/${UZYT}/${REPOBART}.git"

- secure: "315c94b03156c6167973c581e2f62bdeacfd2ae6"

script:

- echo t
- touch foo.txt

after_success:

- MESSAGE="cool"

- git clone git://${GH_REPO}

- mv -f ${FILESBART} ${REPOBART}

- cd ${REPOBART}

- git remote

- git config user.email ${EMAILBART}

- git config user.name ${UZYT}

- git add ${FILESBART}

- git commit -m ${MESSAGE}

- git push "https://${token}@${GH_REPO}" master > /dev/null 2>&1

