sudo: required
dist: trusty
language: bash
script: 
      - sudo apt update -y
      - sudo apt-get install build-essential rsync texinfo libncurses-dev whois unzip bc qt4-linguist-tools -y
      - git clone https://github.com/raspberrypi/noobs.git
      - cd noobs
      - ./BUILDME.sh
