sudo: required
dist: xenial

language: bash

script:
- sudo snap connect discord-bartixxx:gnome-3-26-1604 gnome-3-26-1604
- sudo snap run discord-bartixxx

addons:
  snaps:
    - discord-bartixxx
    - gnome-3-26-1604
