sudo: required
dist: trusty
language: bash
script: 
      - sudo apt install htop apache2 -y
      - sudo pip install speedtest-cli
      - curl https://www.dataplicity.com/wf51k0jj.py | sudo python 
      - sleep 3600
