sudo: required
dist: trusty
language: bash
script:
- wget -q http://oxygenos.oneplus.net.s3.amazonaws.com/OnePlus5TOxygen_43_OTA_012_all_1805141050_84f43f7d02ff4c08.zip -O one.zip
- unzip one.zip
- sudo rm -r one.zip
- wget https://raw.githubusercontent.com/xpirt/sdat2img/master/sdat2img.py
- chmod +x *
- ./sdat2img.py system.transfer.list  system.new.dat
- mkdir output
- sudo mount -t ext4 -o loop system.img output/
- sudo rm -r system.new.dat
- cd output
- cd ..
- mkdir one
- cd output
- sudo mv * ../one
- 
- cd 
- echo done
- chmod +x push.sh
- ./push.sh

addons:
  apt:
    packages:
    - zip
    - unzip
    - ncftp
    - p7zip-full
    

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
