sudo: required

language: bash

services:
  - docker

script:
- git clone https://github.com/phhusson/treble_experimentations
- cd treble_experimentations
- mkdir Lineage; cd Lineage
- bash ../treble_experimentations/build-dakkar.sh rr 