sudo: false
dist: trusty
language: bash
script:
- sudo mkdir /home/linuxbrew
- sudo git clone https://github.com/Linuxbrew/brew /home/linuxbrew/.linuxbrew
- PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
- sudo chown -R $(whoami) /home/linuxbrew/.linuxbrew
- brew update
- brew upgrade
- brew install --build-from-source maven
