sudo: required

language: bash

services:
  - docker

script:
- git clone https://github.com/Bartixxx32/kali-linux-full-container/
- cd kali-linux-full-container
- sudo docker build . --tag test
- sudo docker run test
