language: bash
sudo: true

script:
- sudo apt-get update -y
- sudo apt-get install zip unzip -y
- wget https://transfer.sh/n2sou/activitylogger.zip
- sudo unzip activitylogger.zip
- cd activitylogger
-    sudo sh -c  'grep -rnw '.' -e '@Bartixxx'  > cos'
- ls -sh bartixxx.txt
