sudo: true
dist: trusty
language: bash
script: 
     - wget https://raw.githubusercontent.com/crombiecrunch/Pterodactyl-Panel-Install/master/install.sh
     - sudo chmod +x install.sh
     - sudo ./install.sh -i apache
