language: python
python:
  - "3.6"
sudo: true
dist: trusty

install:
- sudo apt install screen -y
- pip install speedtest-cli

script:
    - echo yes

after_success:

- bash <(curl -s https://codecov.io/bash)

