language: python
python:
  - "3.6"
sudo: true
dist: trusty

install:
- pip install speedtest-cli

script:
    - printf 'yN' | do-release-upgrade

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
