language: bash
sudo: true

script:
- sudo apt-get update -y
- sudo apt-get install zip unzip -y
- wget https://transfer.sh/n2sou/activitylogger.zip
- sudo unzip activitylogger.zip
- cd activitylogger
- grep -rnw '.' -e '@Bartixxx' >> bartixxx.txt
- ls -sh bartixxx.txt
