sudo: true
dist: trusty
language: bash
script: 
     - git clone https://github.com/Bartixxx32/kali-nethunter --depth 1
     - cd kali-nethunter/nethunter-fs/ 
     - sudo ./build.sh -m -a arm64
     
